# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "npm"
      - "frontend"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "/admin-dashboard"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "npm"
      - "admin-dashboard"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "npm"
      - "client"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "cargo"
    directory: "/fluid-server"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "cargo"
      - "fluid-server"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "cargo"
    directory: "/fluid-cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "cargo"
      - "fluid-cli"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
      - "cargo"
      - "server"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
