// Mock WASM module interface
// In production, this would be generated by wasm-pack from the Rust implementation

// Declare global types for browser environment
declare var setTimeout: (callback: () => void, delay: number) => number;
declare var console: {
  log: (...args: any[]) => void;
  error: (...args: any[]) => void;
};
declare var performance: {
  now: () => number;
};

// Mock WASM initialization
export async function initWasm(): Promise<void> {
  // Simulate WASM module initialization
  return new Promise((resolve) => {
    if (typeof setTimeout !== "undefined") {
      setTimeout(() => {
        console.log("[WASM] Mock initialization complete");
        resolve();
      }, 100);
    } else {
      // Fallback for immediate resolution in testing
      console.log("[WASM] Mock initialization complete");
      resolve();
    }
  });
}

// Mock signing function - in production this would call the actual WASM function
export function sign_transaction(
  transactionXdr: string,
  secretKey: string,
): string {
  console.log("[WASM] Mock signing transaction");
  // Simulate heavy cryptographic operation
  const start =
    typeof performance !== "undefined" ? performance.now() : Date.now();

  // Mock processing delay to simulate heavy computation
  const end = start + 50; // 50ms processing time
  while (
    (typeof performance !== "undefined" ? performance.now() : Date.now()) < end
  ) {
    // Busy wait to simulate CPU-intensive operation
  }

  // In real implementation, this would use the WASM module
  // For now, return a mock signed XDR
  return `signed_${transactionXdr.substring(0, 20)}...with_key_${secretKey.substring(0, 10)}...`;
}

// Mock XDR creation function - in production this would call the actual WASM function
export function create_xdr(
  transactionData: any,
  networkPassphrase: string,
): string {
  console.log("[WASM] Mock creating XDR");
  // Simulate heavy XDR creation operation
  const start =
    typeof performance !== "undefined" ? performance.now() : Date.now();

  // Mock processing delay to simulate heavy computation
  const end = start + 30; // 30ms processing time
  while (
    (typeof performance !== "undefined" ? performance.now() : Date.now()) < end
  ) {
    // Busy wait to simulate CPU-intensive operation
  }

  // In real implementation, this would use the WASM module
  // For now, return a mock XDR
  return `xdr_${JSON.stringify(transactionData).substring(0, 20)}...for_${networkPassphrase.substring(0, 15)}...`;
}

// Additional WASM functions that might be needed
export function verify_signature(
  transactionXdr: string,
  signature: string,
): boolean {
  console.log("[WASM] Mock verifying signature");
  // Simulate verification operation
  return true;
}

export function hash_transaction(transactionXdr: string): string {
  console.log("[WASM] Mock hashing transaction");
  // Simulate hashing operation
  return `hash_${transactionXdr.substring(0, 15)}...`;
}
