apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluid.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluid.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "fluid.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: postgres
