{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluid.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluid.labels" . | nindent 4 }}
type: Opaque
stringData:
  FLUID_FEE_PAYER_SECRET: {{ .Values.secrets.fluidFeePayerSecret | quote }}
  DATABASE_ENCRYPTION_KEY: {{ .Values.secrets.databaseEncryptionKey | quote }}
  AUTH_SECRET: {{ .Values.secrets.authSecret | quote }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | quote }}
  ADMIN_PASSWORD_HASH: {{ .Values.secrets.adminPasswordHash | quote }}
{{- end }}
---
{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluid.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluid.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
